#!/bin/sh
set -eu

ROOT="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"

test -f "$ROOT/index.html"
test -f "$ROOT/site.css"
test -f "$ROOT/site.js"
test -f "$ROOT/articles-data.js"

grep -q 'data-intro' "$ROOT/index.html"
grep -q 'data-intro-about' "$ROOT/index.html"
grep -q 'data-enter-home' "$ROOT/index.html"
grep -q 'data-spider' "$ROOT/index.html"
grep -q 'spider__leg spider__leg--8' "$ROOT/index.html"
grep -q 'hanging-spider' "$ROOT/index.html"
grep -q 'data-article-list' "$ROOT/index.html"
grep -q 'data-scroll-tip' "$ROOT/index.html"
grep -q 'data-article-filters' "$ROOT/index.html"
grep -q 'data-panel="about"' "$ROOT/index.html"
grep -q 'data-panel="articles"' "$ROOT/index.html"
grep -q 'data-target="about"' "$ROOT/index.html"
grep -q 'class="github-node"' "$ROOT/index.html"
grep -q 'href="https://github.com/luoshuai990529"' "$ROOT/index.html"
grep -q 'target="_blank" rel="noopener noreferrer"' "$ROOT/index.html"
grep -q 'GITHUB / OPEN SOURCE' "$ROOT/index.html"
grep -q '@luoshuai990529' "$ROOT/index.html"
! grep -q 'data-panel="works"' "$ROOT/index.html"
! grep -q 'data-target="works"' "$ROOT/index.html"
! grep -q '靠近蜘蛛' "$ROOT/index.html"
grep -q 'prefers-reduced-motion' "$ROOT/site.css"
grep -q '@keyframes leg-crawl' "$ROOT/site.css"
grep -q '@keyframes spider-breathe' "$ROOT/site.css"
grep -q '@keyframes spider-blink' "$ROOT/site.css"
grep -q '.hanging-spider:hover' "$ROOT/site.css"
grep -q '4200' "$ROOT/site.js"
! grep -q 'mousemove' "$ROOT/site.js"
grep -q 'aria-pressed' "$ROOT/site.js"
grep -q 'renderArticles' "$ROOT/site.js"
grep -q 'updateScrollTip' "$ROOT/site.js"
grep -q "currentCategory === '全部'" "$ROOT/site.js"
grep -q 'articleList.scrollTop' "$ROOT/site.js"
grep -q "addEventListener('scroll'" "$ROOT/site.js"
grep -q 'keydown' "$ROOT/site.js"
grep -q 'event.preventDefault' "$ROOT/site.js"
grep -q 'showAboutTerminal' "$ROOT/site.js"
grep -q "'Agent 工程', 'RAG'" "$ROOT/site.js"
grep -q 'categoryPriority' "$ROOT/site.js"
grep -q 'bottom:1.2rem' "$ROOT/site.css"
grep -q 'grid-template-rows:auto auto minmax(0,1fr)' "$ROOT/site.css"
grep -q '.stage-panel--articles { display:grid; grid-template-columns:1fr; grid-template-rows:auto auto minmax(0,1fr)' "$ROOT/site.css"
grep -q '.article-list { display:grid' "$ROOT/site.css"
grep -q '.article-scroll-tip' "$ROOT/site.css"
grep -q 'color:var(--muted); background:transparent; border:0; border-radius:0; box-shadow:none' "$ROOT/site.css"
grep -q 'min-height:0' "$ROOT/site.css"
grep -q '.dock:has' "$ROOT/site.css"
grep -q 'left:.5rem; width:calc(50% - .65rem)' "$ROOT/site.css"
grep -q 'translateX(calc(100% + .3rem))' "$ROOT/site.css"
grep -q 'box-shadow:0 .12rem .35rem rgba(26,26,46,.1)' "$ROOT/site.css"
grep -q 'opacity:.76' "$ROOT/site.css"
grep -q '@media (max-width:600px)' "$ROOT/site.css"
grep -q '.github-node {' "$ROOT/site.css"
grep -q '.github-node__circuit' "$ROOT/site.css"
grep -q '.github-node:hover' "$ROOT/site.css"
grep -q '.github-node:focus-visible' "$ROOT/site.css"
grep -q '.github-node { width:100%' "$ROOT/site.css"
! grep -q '.portrait-zone { display:none' "$ROOT/site.css"
test "$(grep -c "^  { category:" "$ROOT/articles-data.js")" -eq 34
test "$(grep -c "href: 'https://github.com/luoshuai990529/blog/blob/main/AI/" "$ROOT/articles-data.js")" -eq 34
! grep -q '../../blog/AI/' "$ROOT/articles-data.js"
grep -q 'class="portrait"' "$ROOT/index.html"
grep -q 'alt="LiberSum99 的手绘头像"' "$ROOT/index.html"
grep -q 'site.css' "$ROOT/index.html"
grep -q 'site.js' "$ROOT/index.html"
grep -q 'articles-data.js' "$ROOT/index.html"
grep -q '>about me<' "$ROOT/index.html"
grep -q '>notes<' "$ROOT/index.html"
grep -q '>Notes<' "$ROOT/index.html"
grep -q '<span>01</span><small>about me</small>' "$ROOT/index.html"
grep -q '<span>02</span><small>notes</small>' "$ROOT/index.html"
grep -q '&gt; whoami' "$ROOT/index.html"
! grep -q '&gt; who am i' "$ROOT/index.html"

echo "person-site checks: PASS"
